#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# run_check "qué comprueba" "comando" — ejecuta y enseña la respuesta, sin abortar.
run_check() {
  local desc="$1" cmd="$2" out=""
  printf '  %s⋯ comprobando:%s %s\n' "$DIM" "$RESET" "$desc"
  out=$(eval "$cmd" 2>&1) || true
  if [[ -n "$out" ]]; then
    while IFS= read -r line; do printf '      %s%s%s\n' "$GREEN" "$line" "$RESET"; done <<< "$out"
  else
    printf '      %s(sin respuesta — puede que aún no haya propagado)%s\n' "$DIM" "$RESET"
  fi
  printf '\n'
}

banner "Cutover de automaticnation.com — WordPress → el sitio nuevo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Backup del WordPress  ·  día −7"
say "Esto es tu marcha atrás. Si el cutover sale mal, es lo único que te"
say "devuelve el sitio actual. No sigas sin hacerlo."
printf '\n'
open_url "https://automaticnation.com/wp-admin/export.php"
step "Entra en el WordPress (te lo acabo de abrir)."
step "Menú lateral: Herramientas → Exportar."
step "Marca 'Todo el contenido' y pulsa 'Descargar archivo de exportación'."
step "Guarda ese .xml FUERA de GoDaddy — Drive, tu disco, donde sea."
printf '\n'
note "Eso guarda los textos y las entradas, pero NO las imágenes."
step "En el panel de GoDaddy, busca la copia de seguridad del hosting y"
step "descarga también los archivos (la carpeta wp-content/uploads)."
printf '\n'
warn "El WordPress no se toca en todo el cutover. Déjalo vivo y pagado 30 días."
pause "Cuando tengas el backup guardado, pulsa Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Bajar el TTL  ·  día −7"
say "Qué es un TTL, en cristiano:"
note "  Cuando alguien visita tu web, su ordenador pregunta '¿dónde está"
note "  automaticnation.com?' y se guarda la respuesta un rato para no"
note "  preguntar cada vez. Ese rato es el TTL."
printf '\n'
say "Ahora está en 1 hora. Eso significa que si el cutover sale mal, tardarías"
say "1 hora en poder volver atrás. Bajándolo a 10 minutos, la marcha atrás"
say "tarda 10 minutos."
printf '\n'
warn "Hazlo AL MENOS un día antes del cambio de DNS, para que el TTL viejo caduque."
printf '\n'
open_url "https://dcc.godaddy.com/control/portfolio/automaticnation.com/settings?tab=dns"
note "Si ese enlace no te deja directamente en la pantalla del DNS, no pasa nada:"
note "GoDaddy cambia la dirección de vez en cuando. Ve a mano por"
note "Mis productos → Dominios → automaticnation.com → DNS."
step "En GoDaddy: Mis productos → Dominios → automaticnation.com → DNS."
step "Busca la fila de tipo 'A' cuyo nombre es '@'. Dale a editar (el lápiz)."
step "En 'TTL' elige 'Personalizado' y pon 600 segundos (= 10 minutos). Guarda."
step "Repite lo mismo en la fila de 'www'."
printf '\n'
warn "NO toques ninguna otra fila. Ni las MX, ni las TXT. Solo el TTL de esas dos."
pause "Cuando lo hayas guardado, pulsa Enter y lo compruebo."
printf '\n'
run_check "el TTL que tienen configurado tus servidores DNS" \
  "dig +noall +answer @ns63.domaincontrol.com automaticnation.com A"
note "El número entre el nombre y 'IN' es el TTL. Debería poner 600."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Bajar la caché del navegador  ·  día −7  (opcional)"
say "Esto NO es DNS. Es otra cosa distinta."
printf '\n'
run_check "cuánto tiempo pide tu web que la guarden" \
  "curl -sI -m 20 https://automaticnation.com/ | grep -i '^cache-control' || echo 'sin respuesta'"
say "Ese 'max-age=2678400' son 31 días. Significa que el navegador de alguien"
say "que te visitó ayer puede seguir enseñándole la web VIEJA hasta 31 días"
say "después del cambio, sin ningún error. Solo la ve antigua."
printf '\n'
warn "Aquí no sé decirte la ruta exacta: depende de cómo tenga GoDaddy montado"
warn "el caché en tu plan de WordPress gestionado. Búscalo por 'Caché' o"
warn "'Rendimiento' en el panel, y si no aparece, pregúntale a su soporte"
warn "cómo bajar el max-age a 300 segundos."
printf '\n'
note "Es el paso menos crítico de todos: no rompe nada, solo hace que algunos"
note "visitantes tarden en ver el sitio nuevo. Si te atascas, sáltalo y sigue."
pause "Enter para continuar."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verificar el dominio en GitHub  ·  día −7"
say "Para qué sirve: si algún día dejas de usar GitHub para esta web, evita"
say "que otra persona pueda reclamar tu dominio ahí y publicar en él."
say "Son 5 minutos y se hace una sola vez."
printf '\n'
note "Ojo: 'devautomaticn' es una cuenta personal, no una organización, así que"
note "esto está en los ajustes de TU cuenta, no en los del repositorio."
printf '\n'
open_url "https://github.com/settings/pages"
step "Asegúrate de estar con la cuenta 'devautomaticn' (arriba a la derecha)."
step "Pulsa 'Add a domain' y escribe: automaticnation.com"
step "GitHub te enseñará dos textos: un NOMBRE que empieza por"
step "  _github-pages-challenge-devautomaticn"
step "y un VALOR largo de letras y números. Déjalo abierto."
printf '\n'
open_url "https://dcc.godaddy.com/control/portfolio/automaticnation.com/settings?tab=dns"
step "En GoDaddy → DNS → 'Añadir registro'."
step "Tipo: TXT"
step "Nombre: pega el NOMBRE que te dio GitHub (solo la parte de delante,"
step "  sin '.automaticnation.com' al final — GoDaddy lo añade solo)."
step "Valor: pega el VALOR largo. Guarda."
printf '\n'
pause "Cuando lo hayas guardado en GoDaddy, pulsa Enter y lo compruebo."
printf '\n'
run_check "que el registro TXT ya se ve desde fuera" \
  "dig +short TXT _github-pages-challenge-devautomaticn.automaticnation.com"
note "Si sale vacío, espera 2 minutos y vuelve a ejecutar este asistente."
printf '\n'
step "Vuelve a la pestaña de GitHub y pulsa 'Verify'."
pause "Cuando GitHub diga 'Verified', pulsa Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "EL CAMBIO  ·  día 0  —  aquí es donde el sitio cambia de verdad"
warn "Este es el único paso que los visitantes notan. Léelo entero antes de tocar nada."
printf '\n'
say "Vas a decirle al mundo que automaticnation.com ya no está en el servidor"
say "de GoDaddy, sino en el de GitHub. Se hace cambiando unas filas del DNS."
printf '\n'
printf '  %s%sLO QUE NO PUEDES TOCAR, BAJO NINGÚN CONCEPTO:%s\n' "$BOLD" "$RED" "$RESET"
say "  · Las 5 filas de tipo MX (ponen aspmx.l.google.com)  ← es el EMAIL"
say "  · La fila TXT que empieza por 'v=spf1'"
say "  · Las dos filas TXT que empiezan por 'google-site-verification'"
printf '\n'
say "Si borras las MX, el correo de la empresa deja de funcionar. Eso es un"
say "incidente mucho peor que cualquier problema de la web."
printf '\n'
step "ANTES DE NADA: haz una captura de pantalla de la lista entera del DNS."
pause "¿Captura hecha? Enter."
printf '\n'
if ! confirm "¿Seguimos y hacemos el cambio ahora?"; then
  say "Perfecto — vuelve a ejecutar el asistente cuando estés listo."
  exit 0
fi
printf '\n'
open_url "https://dcc.godaddy.com/control/portfolio/automaticnation.com/settings?tab=dns"
step "1) Borra la fila de tipo A con nombre '@' que apunta a 160.153.0.120"
step "2) Añade CUATRO filas nuevas, todas tipo A y todas con nombre '@':"
say  "        185.199.108.153"
say  "        185.199.109.153"
say  "        185.199.110.153"
say  "        185.199.111.153"
step "3) Busca la fila 'www'. Debe quedar como tipo CNAME apuntando a:"
say  "        devautomaticn.github.io."
note "     (con el punto final, sí)"
printf '\n'
pause "Cuando lo hayas guardado todo, pulsa Enter y lo compruebo."
printf '\n'
run_check "a dónde apunta ahora tu dominio (deben salir los 185.199.x)" \
  "dig +short automaticnation.com A"
run_check "que el EMAIL sigue intacto (tienen que salir 5 líneas de google)" \
  "dig +short MX automaticnation.com"
printf '\n'
warn "Si las MX no salen, vuelve a GoDaddy y restáuralas AHORA con la captura."
warn "Si los A todavía salen 160.153.0.120, espera 10 minutos: está propagando."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Activar el candado (HTTPS)  ·  día 0, un rato después"
say "GitHub tiene que emitir el certificado de seguridad de tu dominio. No puede"
say "hacerlo hasta que el paso anterior haya propagado. Puede tardar hasta 1 hora."
printf '\n'
note "Mientras tanto el navegador puede avisar de 'sitio no seguro'. Es normal"
note "y se arregla solo. No es un fallo del cutover."
printf '\n'
open_url "https://github.com/devautomaticn/automatic-nation-website/settings/pages"
step "Espera a que ponga 'DNS check successful' (refresca cada tanto)."
step "Cuando salga, marca la casilla 'Enforce HTTPS'."
printf '\n'
pause "Cuando la hayas marcado, pulsa Enter."
printf '\n'
run_check "que tu web responde por https" \
  "curl -sI -m 25 https://automaticnation.com/ | head -1"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Comprobación final  ·  día 0"
run_check "la home" \
  "curl -s -o /dev/null -w 'código %{http_code}' -m 25 https://automaticnation.com/"
run_check "un artículo del blog" \
  "curl -s -o /dev/null -w 'código %{http_code}' -m 25 https://automaticnation.com/how-to-build-a-crm-system/"
run_check "el email (5 líneas = bien)" \
  "dig +short MX automaticnation.com"
printf '\n'
warn "Lo más importante de todo: MÁNDATE UN CORREO DE VERDAD y comprueba que llega."
printf '\n'
say "Lo que queda después, sin prisa:"
step "Purgar la caché en GoDaddy/Cloudflare."
step "En Search Console, enviar https://automaticnation.com/sitemap-index.xml"
step "y retirar el sitemap viejo."
printf '\n'
note "Dile a Claude que ya hiciste el cutover y te pasa el script completo que"
note "comprueba las 64 URLs nuevas y las 15 antiguas de una vez."
printf '\n'
pause

finish
